### ISSUE TITLE
command line basics

### ISSUE THREAD

**Issue by ShubhamRasal** [ShubhamRasal/web-developement-study#1]
What is the command line?
How do you open the command line on your computer?
How can you navigate to a particular directory?
Where will cd on its own navigate you to?
Where will cd .. navigate you to?
How do you display the name of the directory you are currently in?
How do you display the contents of the directory you are currently in?
How do you create a new directory?
How do you create a new file?
How do you destroy a directory or file?
How do you rename a directory or file?

**Comment by swapnil2228** [comment]
#hello i am swapnil
