### ISSUE TITLE
Git Learning

### ISSUE THREAD

**Issue by ShubhamRasal** [ShubhamRasal/web-developement-study#5]
What kind of program is Git?
What are the differences between Git and a text editor in terms of what they save and their record keeping?
Does Git work at a local or remote level?
Does GitHub work at a local or remote level?
Why is Git useful for an individual developer?
Why are Git and GitHub useful for a team of developers?

**Comment by swapnil2228** [comment]
[gitbasics.txt](https://github.com/ShubhamRasal/web-developement-study/files/4912947/gitbasics.txt)

**Comment by swapnil2228** [comment]
completed the assigned work
